### ISSUE TITLE
Impl std::os::fd traits for OwnedFD

### ISSUE THREAD

**Issue by ColonelThirtyTwo** [mahkoh/uapi#17]
std includes several file-descriptor-related traits that `OwnedFD` ought to implement.

Alternatively, use `std::os::fd::OwnedFd` and `std::os::fd::BorrowedFd` instead of `uapi`'s custom implementations.

**Comment by mahkoh** [comment]
>std includes several file-descriptor-related traits that OwnedFD ought to implement.

Please create a PR.

>Alternatively, use std::os::fd::OwnedFd and std::os::fd::BorrowedFd instead of uapi's custom implementations.

The APIs of these std types are very different from the uapi types.

**Comment by mahkoh** [comment]
These traits are now implemented.
