### ISSUE TITLE
Missing `clone`

### ISSUE THREAD

**Issue by e00E** [mahkoh/uapi#6]
https://docs.rs/libc/0.2.82/libc/fn.clone.html
https://docs.rs/nix/0.19.1/nix/sched/fn.clone.html

**Comment by mahkoh** [comment]
I've deliberately omitted `clone`.

1. Any wrapper of `clone` has to be unsafe.
2. There is no sound way to use `clone` in a hosted environment. See e.g. https://sourceware.org/bugzilla/show_bug.cgi?id=10311#c2 ff. Some of the flags might be usable but it's not clear which exactly.

**Comment by mahkoh** [comment]
PS: If you actually want to use `clone`, then I suggest writing a simple wrapper for the `clone3` system call.

**Comment by e00E** [comment]
Thanks for the explanation. Seeing as this is a deliberate decision (I wasn't sure) let's close the issue.
Using clone3 over clone is also what I arrived at after reviewing the api.
